// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
// TEST MOCKERY BOILERPLATE

package interface_annotations

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockServerWithDifferentFile creates a new instance of MockServerWithDifferentFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerWithDifferentFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerWithDifferentFile {
	mock := &MockServerWithDifferentFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerWithDifferentFile is an autogenerated mock type for the ServerWithDifferentFile type
type MockServerWithDifferentFile struct {
	mock.Mock
}

type MockServerWithDifferentFile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerWithDifferentFile) EXPECT() *MockServerWithDifferentFile_Expecter {
	return &MockServerWithDifferentFile_Expecter{mock: &_m.Mock}
}

// HandleRequest provides a mock function for the type MockServerWithDifferentFile
func (_mock *MockServerWithDifferentFile) HandleRequest(path string, handler http.Handler) {
	_mock.Called(path, handler)
	return
}

// MockServerWithDifferentFile_HandleRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRequest'
type MockServerWithDifferentFile_HandleRequest_Call struct {
	*mock.Call
}

// HandleRequest is a helper method to define mock.On call
//   - path string
//   - handler http.Handler
func (_e *MockServerWithDifferentFile_Expecter) HandleRequest(path interface{}, handler interface{}) *MockServerWithDifferentFile_HandleRequest_Call {
	return &MockServerWithDifferentFile_HandleRequest_Call{Call: _e.mock.On("HandleRequest", path, handler)}
}

func (_c *MockServerWithDifferentFile_HandleRequest_Call) Run(run func(path string, handler http.Handler)) *MockServerWithDifferentFile_HandleRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 http.Handler
		if args[1] != nil {
			arg1 = args[1].(http.Handler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerWithDifferentFile_HandleRequest_Call) Return() *MockServerWithDifferentFile_HandleRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerWithDifferentFile_HandleRequest_Call) RunAndReturn(run func(path string, handler http.Handler)) *MockServerWithDifferentFile_HandleRequest_Call {
	_c.Run(run)
	return _c
}
