// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
// TEST MOCKERY BOILERPLATE

package directive_comments

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRequester creates a new instance of MockRequester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequester(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequester {
	mock := &MockRequester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRequester is an autogenerated mock type for the Requester type
type MockRequester struct {
	mock.Mock
}

type MockRequester_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequester) EXPECT() *MockRequester_Expecter {
	return &MockRequester_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockRequester
func (_mock *MockRequester) Get(path string) (string, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequester_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRequester_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - path string
func (_e *MockRequester_Expecter) Get(path interface{}) *MockRequester_Get_Call {
	return &MockRequester_Get_Call{Call: _e.mock.On("Get", path)}
}

func (_c *MockRequester_Get_Call) Run(run func(path string)) *MockRequester_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequester_Get_Call) Return(s string, err error) *MockRequester_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRequester_Get_Call) RunAndReturn(run func(path string) (string, error)) *MockRequester_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequesterWithoutAnnotation creates a new instance of MockRequesterWithoutAnnotation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequesterWithoutAnnotation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequesterWithoutAnnotation {
	mock := &MockRequesterWithoutAnnotation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRequesterWithoutAnnotation is an autogenerated mock type for the RequesterWithoutAnnotation type
type MockRequesterWithoutAnnotation struct {
	mock.Mock
}

type MockRequesterWithoutAnnotation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequesterWithoutAnnotation) EXPECT() *MockRequesterWithoutAnnotation_Expecter {
	return &MockRequesterWithoutAnnotation_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockRequesterWithoutAnnotation
func (_mock *MockRequesterWithoutAnnotation) Get(path string) (string, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequesterWithoutAnnotation_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRequesterWithoutAnnotation_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - path string
func (_e *MockRequesterWithoutAnnotation_Expecter) Get(path interface{}) *MockRequesterWithoutAnnotation_Get_Call {
	return &MockRequesterWithoutAnnotation_Get_Call{Call: _e.mock.On("Get", path)}
}

func (_c *MockRequesterWithoutAnnotation_Get_Call) Run(run func(path string)) *MockRequesterWithoutAnnotation_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequesterWithoutAnnotation_Get_Call) Return(s string, err error) *MockRequesterWithoutAnnotation_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRequesterWithoutAnnotation_Get_Call) RunAndReturn(run func(path string) (string, error)) *MockRequesterWithoutAnnotation_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewFunServer creates a new instance of FunServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFunServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *FunServer {
	mock := &FunServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FunServer is an autogenerated mock type for the Server type
type FunServer struct {
	mock.Mock
}

type FunServer_Expecter struct {
	mock *mock.Mock
}

func (_m *FunServer) EXPECT() *FunServer_Expecter {
	return &FunServer_Expecter{mock: &_m.Mock}
}

// HandleRequest provides a mock function for the type FunServer
func (_mock *FunServer) HandleRequest(path string, handler http.Handler) {
	_mock.Called(path, handler)
	return
}

// FunServer_HandleRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRequest'
type FunServer_HandleRequest_Call struct {
	*mock.Call
}

// HandleRequest is a helper method to define mock.On call
//   - path string
//   - handler http.Handler
func (_e *FunServer_Expecter) HandleRequest(path interface{}, handler interface{}) *FunServer_HandleRequest_Call {
	return &FunServer_HandleRequest_Call{Call: _e.mock.On("HandleRequest", path, handler)}
}

func (_c *FunServer_HandleRequest_Call) Run(run func(path string, handler http.Handler)) *FunServer_HandleRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 http.Handler
		if args[1] != nil {
			arg1 = args[1].(http.Handler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FunServer_HandleRequest_Call) Return() *FunServer_HandleRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *FunServer_HandleRequest_Call) RunAndReturn(run func(path string, handler http.Handler)) *FunServer_HandleRequest_Call {
	_c.Run(run)
	return _c
}
